include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Prints help successfully to stdout, keeps stderr empty, and lists the public CLI surface.")
sr_run(r ARGS --help)
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "Usage:")
sr_assert_stderr_empty(r)
foreach(entry IN LISTS SR_TEST_PUBLIC_CLI_HELP_ENTRIES)
    sr_assert_stdout_contains(r "${entry}")
endforeach()
