include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Uses Script/Executable mode by default and passes child arguments through.")
sr_run(r ARGS "${SR_ECHO_ARGS}" normal-child-argument)
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "ARG1=[normal-child-argument]")
