include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Streams headered child stdout to parent stdout by default.")
sr_run(r ARGS "${SR_STDOUT_CMD}")
sr_assert_exit(r 0)
sr_assert_stdout_txt_header(r "CHILDSTDOUT")
sr_assert_stdout_occurrence_count(r "${SR_TEST_CHILD_STDOUT_MARKER}" 1)
sr_assert_stdout_not_contains(r "${SR_TEST_CHILD_STDERR_MARKER}")
sr_assert_stdout_not_contains(r "${SR_TEST_SRDIAG_TXT_PREFIX}")
