include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(log_dir "${SR_TEST_ROOT}/logs")
sr_run(r ARGS --stdout-dir "${log_dir}" --stdout-emit never "${SR_STDOUT_CMD}")
sr_assert_exit(r 0)
file(GLOB logs LIST_DIRECTORIES false "${log_dir}/*_stdout_success.log")
list(LENGTH logs count)
if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one default-ID stdout log, got ${count}: ${logs}")
endif()
list(GET logs 0 log_path)
get_filename_component(log_name "${log_path}" NAME)
if(NOT log_name MATCHES "^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]_[0-9][0-9]-[0-9][0-9]-[0-9][0-9]Z_pid[0-9]+_stdout_success\\.log$")
    message(FATAL_ERROR "Unexpected default execution-ID log name: ${log_name}")
endif()
