include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Preserves and replays child stdout and stderr produced before a timeout in failure emit mode.")
sr_run(r ARGS --timeout-ms 1500 --stdout-emit failure --stderr-emit failure "${SR_SLEEP_OUTPUT}")
sr_assert_exit(r "${SR_TEST_EXIT_TIMEOUT}")
sr_assert_stdout_contains(r "BEFORE_TIMEOUT")
sr_assert_stderr_contains(r "STDERR_BEFORE_TIMEOUT")
