include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Runs the failure hook and not the success hook when execution times out.")
sr_run(r ARGS --timeout-ms 100 --run-on-success success-hook.cmd --run-on-failure failure-hook.cmd "${SR_SLEEP}")
sr_assert_exit(r "${SR_TEST_EXIT_TIMEOUT}")
sr_wait_for_path("${SR_TEST_ROOT}/failure.marker")
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.3)
sr_assert_path_not_exists("${SR_TEST_ROOT}/success.marker")
