include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Creates a missing relative --cwd directory and runs the child inside it.")
set(relative_cwd "created-cwd")
set(expected_cwd "${SR_TEST_ROOT}/${relative_cwd}")
sr_run(r ARGS --cwd "${relative_cwd}" "${SR_PRINT_CWD}")
sr_assert_exit(r 0)
sr_assert_path_exists("${expected_cwd}")
cmake_path(NATIVE_PATH expected_cwd NORMALIZE expected_cwd_native)
sr_assert_stdout_contains(r "${expected_cwd_native}")
