include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(expected "${SR_TEST_ROOT}/equals-cwd")
sr_run(r ARGS --cwd=equals-cwd "${SR_PRINT_CWD}")
sr_assert_exit(r 0)
cmake_path(NATIVE_PATH expected NORMALIZE expected_native)
sr_assert_stdout_contains(r "${expected_native}")
