include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
file(WRITE "${SR_TEST_ROOT}/not-a-directory" "x")
sr_run(r ARGS --cwd not-a-directory "${SR_OK}")
sr_assert_exit(r "${SR_TEST_EXIT_CLI_ERROR}")
