include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(relative_cwd "cwd with spaces")
set(expected "${SR_TEST_ROOT}/${relative_cwd}")
sr_run(r ARGS --cwd "${relative_cwd}" "${SR_PRINT_CWD}")
sr_assert_exit(r 0)
cmake_path(NATIVE_PATH expected NORMALIZE expected_native)
sr_assert_stdout_contains(r "${expected_native}")
