include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
if(NOT DEFINED ENV{ComSpec} OR "$ENV{ComSpec}" STREQUAL "")
    message(FATAL_ERROR "Windows ComSpec environment variable is not available to the test.")
endif()
string(TOUPPER "$ENV{ComSpec}" explicit_comspec)
sr_run(r ENV "ComSpec=${explicit_comspec}" ARGS --debug "${SR_OK}")
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "${SR_TEST_CHILD_STDOUT_MARKER}")
sr_assert_stderr_contains(r "fullCmdLine=${explicit_comspec}")
