include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Runs the child successfully using the ComSpec fallback when ComSpec is missing.")
sr_run(r UNSET_ENV ComSpec ARGS "${SR_OK}")
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "${SR_TEST_CHILD_STDOUT_MARKER}")
