include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Does not inject code page 65001 by default and enables it with --utf8.")
sr_run(default_cp ARGS --debug "${SR_PRINT_CODEPAGE}")
sr_assert_exit(default_cp 0)
sr_assert_stderr_contains(default_cp "fullCmdLine=")
sr_assert_stderr_not_contains(default_cp "chcp 65001")
sr_run(utf8_cp ARGS --debug --utf8 "${SR_PRINT_CODEPAGE}")
sr_assert_exit(utf8_cp 0)
sr_assert_stdout_contains(utf8_cp "65001")
sr_assert_stderr_contains(utf8_cp "chcp 65001")
