include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Writes child stderr to a combined stderr success TXT log.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-stderr-txt-success")
set(expected_log "${log_dir}/${execution_id}_stderr_success.log")
sr_run(r ARGS --id-base "${execution_id}" --stderr-dir "${log_dir}" "${SR_BOTH_CMD}")
sr_assert_exit(r 0)
sr_assert_file_not_empty("${expected_log}")
sr_assert_file_contains("${expected_log}" "${SR_TEST_CHILD_STDERR_MARKER}")
sr_assert_directory_file_count("${log_dir}" 1)
