include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Writes child stdout and stderr as base64-backed events to the stderr-including-stdout success JSONL log.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-stderr-incl-jsonl-success")
set(expected_log "${log_dir}/${execution_id}_stderr_incl_stdout_success.jsonl")
sr_run(r ARGS --id-base "${execution_id}" --stderr-dir-incl-stdout-jsonl "${log_dir}" "${SR_BOTH_CMD}")
sr_assert_exit(r 0)
sr_assert_file_not_empty("${expected_log}")
sr_assert_file_contains("${expected_log}" "${SR_TEST_CHILD_STDOUT_JSONL_PREFIX}")
sr_assert_file_contains("${expected_log}" "${SR_TEST_CHILD_STDERR_JSONL_PREFIX}")
sr_assert_file_contains("${expected_log}" "${SR_TEST_JSONL_PAYLOAD_BASE64_FIELD}")
sr_assert_directory_file_count("${log_dir}" 1)
