include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Writes child stderr using the default text representation to a child-only failure JSONL log.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-stderr-child-jsonl-failure")
set(expected_log "${log_dir}/${execution_id}_stderr_child_failure.jsonl")
set(expected_payload "${SR_TEST_CHILD_STDERR_MARKER}\r\n")
sr_run(r ARGS --id-base "${execution_id}" --stderr-dir-child-jsonl "${log_dir}" "${SR_FAIL}")
sr_assert_exit(r "${SR_TEST_FAIL_CMD_EXIT_CODE}")
sr_assert_file_not_empty("${expected_log}")
sr_assert_jsonl_default_text_payload("${expected_log}" "ChildStderr" "${expected_payload}")
sr_assert_file_not_contains("${expected_log}" "${SR_TEST_CHILD_STDOUT_JSONL_PREFIX}")
sr_assert_file_not_contains("${expected_log}" "${SR_TEST_SRDIAG_JSONL_PREFIX}")
sr_assert_directory_file_count("${log_dir}" 1)
