include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Writes headered child stdout to a failure TXT log.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-stdout-txt-failure")
set(expected_log "${log_dir}/${execution_id}_stdout_failure.log")
sr_run(r ARGS --id-base "${execution_id}" --stdout-dir "${log_dir}" "${SR_FAIL}")
sr_assert_exit(r "${SR_TEST_FAIL_CMD_EXIT_CODE}")
sr_assert_file_not_empty("${expected_log}")
sr_assert_file_txt_header("${expected_log}" "CHILDSTDOUT")
sr_assert_file_occurrence_count("${expected_log}" "${SR_TEST_CHILD_STDOUT_MARKER}" 1)
sr_assert_file_not_contains("${expected_log}" "${SR_TEST_CHILD_STDERR_MARKER}")
sr_assert_file_not_contains("${expected_log}" "${SR_TEST_SRDIAG_TXT_PREFIX}")
sr_assert_directory_file_count("${log_dir}" 1)
