include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-stdout-jsonl")
set(expected_log "${log_dir}/${execution_id}_stdout_success.jsonl")
sr_run(r ARGS --id-base "${execution_id}" --stdout-dir-jsonl "${log_dir}" --stdout-emit never "${SR_STDOUT_CMD}")
sr_assert_exit(r 0)
sr_assert_file_not_empty("${expected_log}")
sr_assert_file_contains("${expected_log}" "${SR_TEST_CHILD_STDOUT_JSONL_PREFIX}")
sr_assert_file_contains("${expected_log}" "${SR_TEST_JSONL_PAYLOAD_BASE64_FIELD}")
sr_assert_directory_file_count("${log_dir}" 1)
