include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-ret-stderr-incl-always-success")
set(expected_log "${log_dir}/${execution_id}_stderr_incl_stdout_success.log")
sr_run(r ARGS --id-base "${execution_id}" --stderr-dir-incl-stdout "${log_dir}" --stderr-dir-incl-stdout-keep-log always "${SR_BOTH_CMD}")
sr_assert_exit(r 0)
sr_assert_path_exists("${expected_log}")
sr_assert_directory_file_count("${log_dir}" 1)
