include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Keeps the combined stderr log on success under success-only retention.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-ret-stderr-success-success")
set(expected_log "${log_dir}/${execution_id}_stderr_success.log")
sr_run(r ARGS --id-base "${execution_id}" --stderr-dir "${log_dir}" --stderr-dir-keep-log success "${SR_BOTH_CMD}")
sr_assert_exit(r 0)
sr_assert_path_exists("${expected_log}")
sr_assert_directory_file_count("${log_dir}" 1)
