include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Removes the SR-only stderr log on success under failure-only retention.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-ret-stderr-sr-failure-success")
set(expected_log "${log_dir}/${execution_id}_stderr_sr_success.log")
sr_run(r ARGS --id-base "${execution_id}" --debug --stderr-dir-sr "${log_dir}" --stderr-dir-sr-keep-log failure "${SR_OK}")
sr_assert_exit(r 0)
sr_assert_path_not_exists("${expected_log}")
sr_assert_directory_file_count("${log_dir}" 0)
