include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-ret-stderr-incl-success-failure")
set(expected_log "${log_dir}/${execution_id}_stderr_incl_stdout_failure.log")
sr_run(r ARGS --id-base "${execution_id}" --stderr-dir-incl-stdout "${log_dir}" --stderr-dir-incl-stdout-keep-log success "${SR_FAIL}")
sr_assert_exit(r "${SR_TEST_FAIL_CMD_EXIT_CODE}")
sr_assert_path_not_exists("${expected_log}")
sr_assert_directory_file_count("${log_dir}" 0)
