include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Keeps the stdout log on failure under always retention.")
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-ret-stdout-always-failure")
set(expected_log "${log_dir}/${execution_id}_stdout_failure.log")
sr_run(r ARGS --id-base "${execution_id}" --stdout-dir "${log_dir}" --stdout-dir-keep-log always "${SR_FAIL}")
sr_assert_exit(r "${SR_TEST_FAIL_CMD_EXIT_CODE}")
sr_assert_path_exists("${expected_log}")
sr_assert_directory_file_count("${log_dir}" 1)
