include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
set(log_dir "${SR_TEST_ROOT}/logs")
set(execution_id "ctest-ret-failure-success")
set(unexpected_log "${log_dir}/${execution_id}_stdout_success.log")
sr_run(r ARGS --id-base "${execution_id}" --stdout-dir "${log_dir}" --stdout-dir-keep-log failure --stdout-emit never "${SR_STDOUT_CMD}")
sr_assert_exit(r 0)
sr_assert_path_not_exists("${unexpected_log}")
sr_assert_directory_file_count("${log_dir}" 0)
