include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Rejects --timeout-ms when its value is missing.")
sr_run(r ARGS --timeout-ms)
sr_assert_exit(r "${SR_TEST_EXIT_CLI_ERROR}")
sr_assert_stderr_contains(r "Missing value")
