include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Rejects an unknown SilentRunner option with CLI error exit code 2.")
sr_run(r ARGS --unknown-test-option)
sr_assert_exit(r "${SR_TEST_EXIT_CLI_ERROR}")
sr_assert_stdout_empty(r)
sr_assert_stderr_contains(r "Unknown argument: --unknown-test-option")
