include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Accepts --verbose, enables debug diagnostics, and emits verbose diagnostics.")
sr_run(r ARGS --verbose "${SR_OK}")
sr_assert_exit(r 0)
sr_assert_stderr_contains(r "fullCmdLine=")
sr_assert_stderr_contains(r "[severity=VERBOSE]")
