include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Runs the selected hook with the configured --cwd working directory.")
file(MAKE_DIRECTORY "${SR_TEST_ROOT}/hook-workdir")
sr_run(r ARGS --cwd hook-workdir --run-on-success hook-cwd.cmd "${SR_OK}")
sr_assert_exit(r 0)
set(result_file "${SR_TEST_ROOT}/hook-cwd.txt")
sr_wait_for_path("${result_file}")
set(expected "${SR_TEST_ROOT}/hook-workdir")
cmake_path(NATIVE_PATH expected NORMALIZE expected_native)
sr_assert_file_contains("${result_file}" "CWD=[${expected_native}]")
