include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Does not run the failure hook when the child execution succeeds.")
sr_run(r ARGS --run-on-failure failure-hook.cmd "${SR_OK}")
sr_assert_exit(r 0)
execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 0.3)
sr_assert_path_not_exists("${SR_TEST_ROOT}/failure.marker")
