include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Suppresses child stdout and stderr from parent stderr in failure mode when the child succeeds.")
sr_run(r ARGS --stderr-emit-incl-stdout failure "${SR_BOTH_CMD}")
sr_assert_exit(r 0)
sr_assert_stderr_not_contains(r "${SR_TEST_CHILD_STDOUT_MARKER}")
sr_assert_stderr_not_contains(r "${SR_TEST_CHILD_STDERR_MARKER}")
