include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Emits headered child stderr only in stream mode when the child succeeds, without SR diagnostics.")
sr_run(r ARGS --stderr-emit-child stream --stderr-dir-sr "${SR_TEST_ROOT}/sr-diag" "${SR_BOTH_CMD}")
sr_assert_exit(r 0)
sr_assert_stderr_txt_header(r "CHILDSTDERR")
sr_assert_stderr_occurrence_count(r "${SR_TEST_CHILD_STDERR_MARKER}" 1)
sr_assert_stderr_not_contains(r "${SR_TEST_CHILD_STDOUT_MARKER}")
sr_assert_stderr_not_contains(r "${SR_TEST_SRDIAG_TXT_PREFIX}")
