include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Emits child stdout in stream mode when the child succeeds.")
sr_run(r ARGS --stdout-emit stream "${SR_STDOUT_CMD}")
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "${SR_TEST_CHILD_STDOUT_MARKER}")
