#include "HelpGenerator.h"

#include "SRTypes.h"

namespace HelpGenerator {

std::wstring Generate() {
    std::wstring err =
        L"Usage of v1.0.0:\n"
        L"  SilentRunner.exe [options] <script-or-exe> [args...]\n"
        L"      Execute script or executable via cmd.exe /d /s /c.\n"
        L"      The file must be executable in the user's Windows environment.\n"
        L"      Some characters may trigger cmd.exe shell operations or affect interpretation:\n"
        L"      chaining (&, &&, ||), output piping (|), redirection (>, <),\n"
        L"      grouping ( ), escaping (^), or variable expansion (%...%, !...!)\n"
        L"      Their presence may be logged for debugging.\n"
        L"      For complex command logic, use a .cmd or other script file (multi-line supported).\n"
        L"  SilentRunner.exe [options] -c \"<command>\"\n"
        L"      Execute raw command string via cmd.exe /d /s /c.\n"
        L"      The command must be passed as a single \"<command>\" argument.\n"
        L"\n"
        L"Paths:\n"
        L"      Paths containing spaces must be quoted.\n"
        L"      Relative paths are resolved against SilentRunner's current working directory (inherited from parent process),\n"
        L"      not against --cwd.\n"
        L"\n"
        L"Common options:\n"
        L"  --help\n"
        L"      Show this help message and exit.\n"
        L"  --debug\n"
        L"      Enable debug diagnostics.\n"
        L"  --verbose\n"
        L"      Enable verbose diagnostics (implies --debug).\n"
        L"  --probe-dir <dir>\n"
        L"      Enables detailed internal probe logging. Intended for development and advanced diagnostics.\n"
        L"      Output format may change between versions.\n"
        L"      Probe logs bypass the ExecutionTimeline and are written directly to the probe log file.\n"
        L"  --inherit-stdin\n"
        L"      Inherit parent stdin instead of using NUL.\n"
        L"  --utf8 or --utf-8\n"
        L"      Force UTF-8 code page (chcp 65001) for the child process.\n"
        L"  --timeout-ms <ms>\n"
        L"      Terminate the child process after the specified timeout (milliseconds).\n"
        L"  --cwd <dir>\n"
        L"      Set the working directory for the main child process and run-on-* hooks.\n"
        L"      If omitted, SilentRunner uses its inherited working directory.\n"
        L"\n"
        L"Run hooks:\n"
        L"  --run-on-success <path>\n"
        L"  --run-on-failure <path>\n"
        L"      Execute hook file via cmd.exe /d /s /c.\n"
        L"      The file must exist and be directly executable by cmd.exe.\n"
        L"      No arguments are supported; execution context is provided via environment variables only:\n"
        L"      SILENTRUNNER_EXIT_CODE, SILENTRUNNER_EXECUTION_ID,\n"
        L"      SILENTRUNNER_STDOUT_LOG, SILENTRUNNER_STDOUT_JSONL_LOG,\n"
        L"      SILENTRUNNER_STDERR_LOG, SILENTRUNNER_STDERR_JSONL_LOG,\n"
        L"      SILENTRUNNER_STDERR_CHILD_LOG, SILENTRUNNER_STDERR_CHILD_JSONL_LOG,\n"
        L"      SILENTRUNNER_STDERR_SR_LOG, SILENTRUNNER_STDERR_SR_JSONL_LOG,\n"
        L"      SILENTRUNNER_STDERR_INCL_STDOUT_LOG, SILENTRUNNER_STDERR_INCL_STDOUT_JSONL_LOG.\n"
        L"      Log environment variables are empty if the corresponding log is not kept after execution\n"
        L"      (see --stdout-dir-keep-log, --stderr-dir-keep-log,\n"
        L"      --stderr-dir-child-keep-log, --stderr-dir-sr-keep-log,\n"
        L"      --stderr-dir-incl-stdout-keep-log).\n"
        L"      The success hook runs only when the child exit code is 0.\n"
        L"      The failure hook runs only when the child exit code is non-zero.\n"
        L"      Run hooks are started detached. SilentRunner logs only whether the hook process\n"
        L"      was started successfully; hook output is not captured.\n"
        L"\n"
        L"Execution ID:\n"
        L"  --id-prefix <value>\n"
        L"  --id-base <value>\n"
        L"  --id-suffix <timestamp|pid|timestamp+pid|pid+timestamp>\n"
        L"      All three components are optional and may be used independently.\n"
        L"      The execution ID is formed from the specified components in this order:\n"
        L"      id-prefix + id-base + id-suffix.\n"
        L"      If none is specified, the execution ID defaults to timestamp+pid (UTC).\n"
        L"\n"
        L"Output routing options:\n"
        L"  --stdout-emit <mode>\n"
        L"      Control how stdout is emitted to the parent.\n"
        L"  --stderr-emit <mode>\n"
        L"      Emit stderr-sr-and-child to the parent (SilentRunner diagnostics plus child stderr).\n"
        L"  --stderr-emit-child <mode>\n"
        L"      Emit stderr-child to the parent (child stderr only).\n"
        L"  --stderr-emit-sr <mode>\n"
        L"      Emit stderr-sr to the parent (SilentRunner diagnostics only).\n"
        L"  --stderr-emit-incl-stdout <mode>\n"
        L"      Emit stderr-sr-and-child-incl-stdout to the parent (SilentRunner diagnostics plus child stderr and stdout).\n"
        L"      The four stderr emit options are mutually exclusive.\n"
        L"\n"
        L"  --stdout-max-buffer-bytes <bytes>\n"
        L"  --stderr-max-buffer-bytes <bytes>\n"
        L"  --std-total-max-buffer-bytes <bytes>\n"
        L"      Limit RAM used when buffering stdout/stderr for End/Success/Failure replay.\n"
        L"      stdout/stderr limits are per-stream; std-total-max-buffer-bytes is the total limit.\n"
        L"      Recommended especially when no log file is configured.\n"
        L"\n"
        L"  --stdout-dir <dir>\n"
        L"  --stderr-dir <dir>\n"
        L"      Write stdout and stderr-sr-and-child to log files.\n"
        L"      stderr-sr-and-child contains SilentRunner diagnostics plus child stderr.\n"
        L"      The directory is created automatically if it does not exist.\n"
        L"      Buffering is not needed for End/Success/Failure emit modes when log files are used.\n"
        L"  --stderr-dir-child <dir>\n"
        L"      Write stderr-child to log files (child stderr only).\n"
        L"  --stderr-dir-sr <dir>\n"
        L"      Write stderr-sr to log files (SilentRunner diagnostics only).\n"
        L"  --stderr-dir-incl-stdout <dir>\n"
        L"      Write stderr-sr-and-child-incl-stdout to log files.\n"
        L"  --stdout-dir-jsonl <dir>\n"
        L"  --stderr-dir-jsonl <dir>\n"
        L"  --stderr-dir-child-jsonl <dir>\n"
        L"  --stderr-dir-sr-jsonl <dir>\n"
        L"  --stderr-dir-incl-stdout-jsonl <dir>\n"
        L"      Write structured JSONL output events to log files.\n"
        L"  --stdout-dir-keep-log <mode>\n"
        L"  --stderr-dir-keep-log <mode>\n"
        L"  --stderr-dir-child-keep-log <mode>\n"
        L"  --stderr-dir-sr-keep-log <mode>\n"
        L"  --stderr-dir-incl-stdout-keep-log <mode>\n"
        L"      Control when log files are kept or deleted.\n"
        L"      JSONL outputs share the same keep-log policy as the corresponding TXT stream.\n"
        L"\n"
        L"Emit modes:\n";
    SR::AppendEmitModeHelpForBoth(err);

    err += L"\nKeep-log modes:\n";
    SR::AppendKeepLogModeHelp(err);

    err += L"\nFor examples and detailed usage, see documentation.";
    return err;
}

} // namespace HelpGenerator
