include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Rejects leading whitespace in --stdout-dir.")
set(bad_path " badpath")
sr_run(r ARGS --stdout-dir "${bad_path}" "${SR_OK}")
sr_assert_exit(r "${SR_TEST_EXIT_CLI_ERROR}")
