include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Passes --help to the child when it appears after the child command.")
sr_run(r ARGS "${SR_ECHO_ARGS}" --help)
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "ARG1=[--help]")
