include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Executes a raw command supplied with -c.")
sr_run(r ARGS -c "echo RAW_COMMAND_OK")
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "RAW_COMMAND_OK")
