include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
sr_run(r ARGS -c "echo REDIRECT_OK>raw-output.txt")
sr_assert_exit(r 0)
sr_assert_file_contains("${SR_TEST_ROOT}/raw-output.txt" "REDIRECT_OK")
