include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init()
sr_run(r ARGS "${SR_ECHO_ARGS}" "hello world" second)
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "ARG1=[hello world]")
sr_assert_stdout_contains(r "ARG2=[second]")
