include("${SR_TESTS_SOURCE_DIR}/helpers/SRTest.cmake")
sr_test_init(DESCRIPTION "Runs a script whose path contains spaces.")
set(dir "${SR_TEST_ROOT}/scripts with spaces")
file(MAKE_DIRECTORY "${dir}")
file(COPY "${SR_OK}" DESTINATION "${dir}")
set(script "${dir}/ok.cmd")
sr_run(r ARGS "${script}")
sr_assert_exit(r 0)
sr_assert_stdout_contains(r "${SR_TEST_CHILD_STDOUT_MARKER}")
